### ISSUE TITLE
7 Files we need to create?

### ISSUE THREAD

**Issue by shichen85** [GameMakerDiscord/Gamemaker-Rubber#9]
Hello!

Do we need to create all 7 files? 

            * a. build.bff
            * b. macros.json
            * c. preferences.json
            * d. steam_options.yy (json)
            * e. targetoptions.json
            * f. MainOptions.json
            * g. PlatformOptions.json

In my experience, having 3 of them is enough to run `Igor.exe` for Android and PC:
           * a. build.bff
           * b. macros.json
           * e. targetoptions.json

And these files will be generated automatically:
            * f. MainOptions.json
            * g. PlatformOptions.json
            * c. preferences.json
            * d. steam_options.yy (json)

**Comment by paperclover** [comment]
oh well thats useful to know, I just looked at the folder and saw all 7 files and just decied to generate all 7... So i guess stuff could be made way simpler then, ill probably just remove the extras once i verify everything else works.

**Comment by shichen85** [comment]
Sounds good! I have also tested on more platforms after I left the comment, and just using 3 files worked for:
1. iOS
2. MacOS
3. Nintendo Switch
I will be testing Ubuntu on Monday once I have access to a machine.

`Igor.exe` uses different keys for different platforms:

## Build

1. PC: `-- Windows PackageZip`
2. Switch: `-- Switch Package`
3. Android: `-- Android Package`
4. macOS: `-- Mac Package`
5. Ubuntu: `-- Linux Package`
6. iOS: `-- iOS Package`

## Clean Cache

1. PC: `-- windows Clean`
2. Switch: `-- switch Clean`
3. Android: `-- android Clean`
4. macOS: `-- mac Clean` Requires romote client connection
5. Ubuntu: ` -- linux Clean` Requires romote client connection
6. iOS: `-- ios Clean` Requires remote client connection

And simply changing the `configure` entry in `build.bff` and `VM` or `YYC` in `targetoptions.json` allows us to build for different configurations.

**Comment by paperclover** [comment]
Fixed by #12
